name: SMA50 Alert

on:
  schedule:
    - cron: "45 11 * * 1-5"

  workflow_dispatch:

jobs:
  check_sma:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: Run Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python sma50alert.py
      - name: Run Upstox Alerts
        continue-on-error: true
        env:
          UPSTOX_API_KEY: ${{ secrets.UPSTOX_API_KEY }}
          UPSTOX_API_SECRET: ${{ secrets.UPSTOX_API_SECRET }}
          UPSTOX_ACCESS_TOKEN: ${{ secrets.UPSTOX_ACCESS_TOKEN }}
        run: python upstox_alerts.py
